### ISSUE TITLE
Implement Datamodel Interfaces

### ISSUE THREAD

**Issue by 94726** [LeoTuet/backend-we-want-to-sleep#2]
```
interface Vote {
  _id: string;
  token: string;
  ballotID: string;
  vote: string;
  votedAt: Date;
}

interface Ballot {
  _id: string;
  running: boolean;
  options: string[];
}

interface Token {
  _id: string;
  token: string;
  valid: boolean;
  createdAt: Date;
}
```

**Comment by quintus-luis** [comment]
Hier sollten wir noch bei dem Ballot und dem Token speichern von welchem Admin das erstellt wurde.

Also eine Admin Db noch mit userName und password und dann jeweils gespeichert wer die aktion ausgelöst hat

**Comment by 94726** [comment]
sollte Vote nicht eher `tokenID` statt `token` haben? @quintus-luis

**Comment by quintus-luis** [comment]
mmh. Würde schon eher das token speichern. bzw. vllt die token als id setzen.
Also das _id generiert die mongo ja automatisch. Aber man kann glaube ich manuell setzen, dass man lieber ein anderes Attribut als PK haben will. Da könnten wir den Token nehmen

**Comment by 94726** [comment]
Hört sich auch gut an. 
Dachte nur, falls man in der API, einen ganzen Vote zurück geben würde,
![image](https://user-images.githubusercontent.com/58269084/152642286-068d6971-b8af-4ea9-80ef-2ab6726f3395.png)
Hätte man halt den token halt direkt exposed, bzw. muss den halt extra rausnehmen.

**Comment by quintus-luis** [comment]
An welcher Stelle würdest du den denn zurückgeben? Maximal nach dem Voten ja eigentlich und dann ist er ja eh schon im Frontend

**Comment by quintus-luis** [comment]
Und Token als PK geht doch nicht -> Mehrere Wahlgänge

**Comment by 94726** [comment]
> An welcher Stelle würdest du den denn zurückgeben? Maximal nach dem Voten ja eigentlich und dann ist er ja eh schon im Frontend

Beim betreten der Seite müssen wir doch gegebenenfalls den abgegebenen Vote fetchen

**Comment by quintus-luis** [comment]
> > An welcher Stelle würdest du den denn zurückgeben? Maximal nach dem Voten ja eigentlich und dann ist er ja eh schon im Frontend
> 
> Beim betreten der Seite müssen wir doch gegebenenfalls den abgegebenen Vote fetchen

Ne dafür war doch unser token-status

**Comment by 94726** [comment]
Ne würde token-status nur {exists: bool, valid: bool} machen.

Imagine:
User hat schon für 8:15 gevoted.
User geht nochmal auf die Page.
Wir wollen gucken ob sein token existiert und valid ist.
Dann wollen wir anzeigen, wann und was er gevoted hat (Infos aus /vote/ballot/token).

Dadurch, dass wir eh den ganzen vote fetchen müssen, brauchen wir kein bool im status der sagt ob man schon gevoted hat.

**Comment by quintus-luis** [comment]
Mein Plan war eher das nicht anzuzeigen. Also ich hätte nur einfach bei dem status, der schon gevotet ist, die Abstimmungssection ausgeblendet. 
Dann brauchen wir nur den Status und müssen das andere nicht fetchen
