### ISSUE TITLE
Translated VoteOptions

### ISSUE THREAD

**Issue by LeoTuet** [LeoTuet/backend-we-want-to-sleep#56]
In order to support full translation we need to update the [VotingOptions ](https://github.com/LeoTuet/backend-we-want-to-sleep/blob/5c53b38e568d99378317e48694a6a30d780ff428/src/repositories/schemas.ts#L27)to have a English and German label.

The same goes for the [question](https://github.com/LeoTuet/backend-we-want-to-sleep/blob/main/src/repositories/schemas.ts#L15).

- [x] Questionupdated
- [x] VoteOptions updated

**Comment by 94726** [comment]
After further discussion, we decided on a implementation.
The question value should be a JSON-object containing `de`, `en` (possible other languages). We would then store the question inside these. 

Examples:

```ts
ballot: {
  "question": {
    "en": "Question"
    "de": "Frage"
  }
}
```

```ts
VoteOption: {
  "label": {
    "en": "text of the option"
    "de": "text der option"
  }
}
```

**Comment by LeoTuet** [comment]
Already merged.
