### ISSUE TITLE
Drop token from vote

### ISSUE THREAD

**Issue by marcschwaiger** [LeoTuet/backend-we-want-to-sleep#58]
Only show the result after voting. 
There is no need to show your own vote unless there is a possibility to change your vote. 

Save tokens used to vote in ballot instead of saving the token in vote.

**Comment by 94726** [comment]
> And then generating a new token to show the vote would be a better idea

More details

**Comment by 94726** [comment]
And add a list of voted ballots to token. Otherwise we don't have a way of checking whether a token was already used to vote.
