### ISSUE TITLE
Authentication for Metrics

### ISSUE THREAD

**Issue by LeoTuet** [LeoTuet/backend-we-want-to-sleep#61]
### Feature Description

I need a way to Authenticate with an API Key for Grafana DataSources.
The API Key should be contained in the Headers.

I guess the keys can be stored in the MongoDB.

### Is this feature valuable for other users as well and why?

No it isnt we simply dont want to expose our metrics endpoint to everyone.

**Comment by 94726** [comment]
Could you re-read the questions and your answers please?
